use chrono::Utc;
use serde::{Deserialize, Serialize};
use tauri::State;

use crate::models::visual_identity::{NoteVisualIdentity, VisualIdentitySeed};
use crate::services::visual_identity::generate_visual_identity_seed;
use crate::state::AppState;

#[derive(Debug, Serialize, Deserialize)]
pub struct GenerateVisualIdentityParams {
    pub note_id: String,
    pub title: String,
    pub content: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct VisualIdentityResponse {
    pub seed: VisualIdentitySeed,
    pub identity: Option<NoteVisualIdentity>,
}

/// Generate visual identity seed from note title and content
/// This returns the seed values that the frontend will use to generate the actual visual pattern
#[tauri::command]
pub async fn generate_note_visual_identity_seed(
    state: State<'_, AppState>,
    params: GenerateVisualIdentityParams,
) -> Result<VisualIdentitySeed, String> {
    let seed = generate_visual_identity_seed(&params.title, &params.content);
    Ok(seed)
}

/// Get stored visual identity for a note
#[tauri::command]
pub async fn get_note_visual_identity(
    state: State<'_, AppState>,
    note_id: String,
) -> Result<Option<NoteVisualIdentity>, String> {
    state
        .db
        .get_visual_identity(&note_id)
        .map_err(|e| format!("Failed to get visual identity: {}", e))
}

/// Store visual identity data (called from frontend after generation)
#[tauri::command]
pub async fn save_note_visual_identity(
    state: State<'_, AppState>,
    note_id: String,
    gradient_colors: Vec<String>,
    pattern_type: String,
    pattern_data: Option<String>,
    image_data: Option<String>,
) -> Result<(), String> {
    let now = Utc::now().timestamp_millis();
    state
        .db
        .insert_visual_identity(
            &note_id,
            &gradient_colors,
            &pattern_type,
            pattern_data.as_deref(),
            image_data.as_deref(),
            now,
            now,
        )
        .map_err(|e| format!("Failed to save visual identity: {}", e))?;
    Ok(())
}

/// Regenerate visual identity for a note
/// This deletes the old identity so the frontend will regenerate it
#[tauri::command]
pub async fn regenerate_note_visual_identity(
    state: State<'_, AppState>,
    note_id: String,
) -> Result<(), String> {
    // Delete old identity (frontend will regenerate on next access)
    state
        .db
        .delete_visual_identity(&note_id)
        .map_err(|e| format!("Failed to delete old visual identity: {}", e))?;

    Ok(())
}

/// Regenerate visual identities for all notes (batch operation)
/// This deletes existing visual identities so they can be regenerated by the frontend
#[tauri::command]
pub async fn regenerate_all_visual_identities(
    state: State<'_, AppState>,
) -> Result<u32, String> {
    let note_ids = state
        .db
        .list_all_note_ids()
        .map_err(|e| format!("Failed to list notes: {}", e))?;

    let mut count = 0;
    for note_id in note_ids {
        // Delete old identity if exists (frontend will regenerate on next access)
        if state.db.delete_visual_identity(&note_id).is_ok() {
            count += 1;
        }
    }

    Ok(count)
}
