use std::fs;
use std::path::Path;

use crate::error::AppResult;

const CLAUDE_MD: &str = "@AGENTS.md\n";

const AGENTS_MD: &str = r#"# Notes vault — agent guide

This folder is a **Markd** vault: a plain-Markdown knowledge base. You can read
and edit it directly with ordinary file tools.

## Layout

- Markdown files in this root are notes. Filename (minus `.md`) is the note
  title. Subfolders are real folders and nest freely. **This is the main
  surface — read and write here.**
- `.markd/` — app data managed by Markd: `todos.json`, `bookmarks.json`, tag
  registries, and `assets/` (pasted images). Safe to read; edit only if you
  follow the shapes below.
- `CLAUDE.md` / `AGENTS.md` — this guide (generated by Markd if missing; your
  edits are kept).

## Note format

- Plain Markdown (CommonMark + GFM — tables, task lists, fenced code).
- A note may begin with a YAML frontmatter block delimited by `---`.
  **Preserve it** when editing; Markd renders it as an editable properties
  panel and only authors it after an explicit user action.
- Internal page links are Markdown links whose target is relative to this
  vault root, e.g. `[Roadmap](projects/roadmap.md)`. `[[wiki]]` and
  `[[target|alias]]` links are also understood.
- Images reference vault-relative paths under `.markd/assets/`.

## Editing rules

- Create a note by writing `<Title>.md` in this folder. Rename a note by renaming the
  file — the filename is the title; there are no IDs or required frontmatter.
- Keep content plain Markdown; don't invent app-specific syntax.
- Markd picks up external changes when its window regains focus.

## App data shapes (`.markd/`)

`todos.json` — array of:

```json
{ "id": "uuid", "text": "string", "done": false, "createdAt": 0, "completedAt": null, "tags": [] }
```

`bookmarks.json` — array of:

```json
{ "id": "uuid", "url": "string", "title": "string", "image": null, "favicon": null, "metaFetched": false, "tags": [], "createdAt": 0 }
```

`todo_tags.json` / `bookmark_tags.json` — array of tag-name strings (the
registry). Timestamps are epoch milliseconds; generate a UUID and set
`createdAt` when adding an item.
"#;

/// Write `CLAUDE.md` and `AGENTS.md` at the vault root so coding agents know
/// how to work with the vault. Only known layout phrases from Markd's previous
/// generated guide are updated; a user's own guide is never overwritten.
pub fn ensure(root: &Path) -> AppResult<()> {
    let agents = root.join("AGENTS.md");
    write_if_missing(&agents, AGENTS_MD)?;
    update_legacy_layout_guide(&agents)?;
    write_if_missing(&root.join("CLAUDE.md"), CLAUDE_MD)?;
    Ok(())
}

fn update_legacy_layout_guide(path: &Path) -> AppResult<()> {
    let existing = fs::read_to_string(path)?;
    if !existing.starts_with("# Notes vault — agent guide")
        || !existing.contains("- `notes/` — the notes")
    {
        return Ok(());
    }
    let updated = existing
        .replace(
            "- `notes/` — the notes, as plain `.md` files. Filename (minus `.md`) is the\n  note title. Subfolders are real folders and nest freely. **This is the main\n  surface — read and write here.**",
            "- Markdown files in this root are notes. Filename (minus `.md`) is the\n  note title. Subfolders are real folders and nest freely. **This is the main\n  surface — read and write here.**",
        )
        .replace("relative\n  to `notes/`,", "relative to this\n  vault root,")
        .replace(
            "Create a note by writing `notes/<Title>.md`.",
            "Create a note by writing `<Title>.md` in this folder.",
        );
    fs::write(path, updated)?;
    Ok(())
}

fn write_if_missing(path: &Path, contents: &str) -> AppResult<()> {
    if !path.exists() {
        fs::write(path, contents)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn creates_both_guides() {
        let dir = tempdir().unwrap();
        ensure(dir.path()).unwrap();
        assert!(dir.path().join("AGENTS.md").exists());
        assert_eq!(
            fs::read_to_string(dir.path().join("CLAUDE.md")).unwrap(),
            CLAUDE_MD,
        );
    }

    #[test]
    fn does_not_overwrite_existing() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("AGENTS.md"), "mine").unwrap();
        ensure(dir.path()).unwrap();
        assert_eq!(
            fs::read_to_string(dir.path().join("AGENTS.md")).unwrap(),
            "mine",
        );
    }

    #[test]
    fn updates_the_generated_legacy_layout_guidance() {
        let dir = tempdir().unwrap();
        fs::write(
            dir.path().join("AGENTS.md"),
            "# Notes vault — agent guide\n\n- `notes/` — the notes, as plain `.md` files. Filename (minus `.md`) is the\n  note title. Subfolders are real folders and nest freely. **This is the main\n  surface — read and write here.**\n- Internal page links are Markdown links whose target is a note path relative\n  to `notes/`, e.g. `[Roadmap](projects/roadmap.md)`.\nCreate a note by writing `notes/<Title>.md`.\n",
        )
        .unwrap();

        ensure(dir.path()).unwrap();

        let guide = fs::read_to_string(dir.path().join("AGENTS.md")).unwrap();
        assert!(!guide.contains("- `notes/` — the notes"));
        assert!(guide.contains("Markdown files in this root are notes"));
        assert!(guide.contains("relative to this\n  vault root"));
        assert!(!guide.contains("`notes/<Title>.md`"));
        assert!(guide.contains("`<Title>.md` in this folder"));
    }
}
